@extends('dasgboard.layouts.app')

@section('title', $pageTitle)

@push('styles')
<style>
.orders-heading-actions{display:flex;align-items:center;gap:12px}.orders-total{display:inline-flex;align-items:center;gap:7px;padding:9px 13px;border:1px solid #f0e5dc;border-radius:10px;background:#fff;color:#76665d}.orders-total strong{color:#2a180f;font-size:1.08rem}.create-order-button{display:inline-flex;align-items:center;gap:7px;padding:11px 16px;border-radius:10px;background:#ff6b00;color:#fff;text-decoration:none;font-weight:700;box-shadow:0 8px 20px #ff6b0030;transition:.2s}.create-order-button:hover{background:#e85f00;color:#fff;transform:translateY(-1px)}
.orders-flash{margin-bottom:18px;padding:12px 15px;border:1px solid #ffd9bd;border-radius:10px;background:#fff0e3;color:#b94d00;font-weight:600}.orders-panel{padding:0;overflow:hidden}.orders-panel .table-wrap{padding:0 20px 6px}.orders-table{min-width:1460px;table-layout:fixed;white-space:normal}.orders-table th,.orders-table td{padding:15px 10px;vertical-align:top}.orders-table th{position:sticky;top:0;z-index:2;background:#fff;color:#76665d;font-size:.78rem;letter-spacing:.02em;text-transform:uppercase}.orders-table tbody tr{transition:background .18s ease}.orders-table tbody tr:hover{background:#fffaf6}.orders-table td{font-size:.92rem;line-height:1.45;overflow-wrap:break-word}.orders-table th:nth-child(1){width:135px}.orders-table th:nth-child(2){width:155px}.orders-table th:nth-child(3){width:280px}.orders-table th:nth-child(4){width:130px}.orders-table th:nth-child(5){width:175px}.orders-table th:nth-child(6){width:200px}.orders-table th:nth-child(7){width:80px}.orders-table th:nth-child(8){width:90px}.orders-table th:nth-child(9){width:175px}.orders-table th:nth-child(10){width:120px}
.order-number{display:inline-flex;padding:4px 9px;border-radius:999px;background:#fff0e3;color:#d95800;font-weight:800}.order-note{display:block;margin-top:7px;color:#c9570a;font-size:.77rem;line-height:1.35}.order-note a{color:#0d6efd;font-weight:700}.customer-name,.product-copy{display:block;color:#2a180f;font-weight:700}.order-contact{white-space:nowrap}.order-email{word-break:break-word}.order-address{color:#4d433d}.order-quantity,.order-total{font-weight:700}.order-total{color:#d95800;white-space:nowrap}
.order-status-form{display:grid;gap:7px}.order-status-form select,.order-status-form button{width:100%;min-width:0;min-height:38px;border-radius:8px;font:inherit}.order-status-form select{padding:7px 9px;border:1px solid #e7d9cf;background:#fff;color:#2a180f}.order-status-form button{border:0;background:#ff6b00;color:#fff;cursor:pointer;font-weight:700}.order-status-form button:hover{background:#e85f00}.order-actions{display:grid;gap:7px}.order-actions form{margin:0}.order-action{display:flex;align-items:center;justify-content:center;width:100%;min-height:38px;gap:6px;padding:7px 9px;border:0;border-radius:8px;cursor:pointer;font:inherit;font-weight:600;text-decoration:none}.order-action--edit{background:#fff0e3;color:#c95400}.order-action--delete{background:#fdebec;color:#c62828}.order-action:hover{filter:brightness(.97)}
.orders-panel .pagination-wrap{padding:0 20px 20px}
@media(max-width:767.98px){.page-heading{align-items:stretch;flex-direction:column}.orders-heading-actions{justify-content:space-between}.create-order-button{justify-content:center}.orders-panel{overflow:visible;border:0;background:transparent;box-shadow:none;padding:0!important}.orders-panel .table-wrap{overflow:visible;padding:0}.orders-table{display:block;min-width:0!important}.orders-table thead{display:none}.orders-table tbody{display:grid;gap:14px}.orders-table tr{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));overflow:hidden;border:1px solid #f0dfd2;border-radius:14px;background:#fff;box-shadow:0 7px 22px #2a180f0d}.orders-table tbody tr:hover{background:#fff}.orders-table td{display:block;min-width:0;padding:11px 14px;border-bottom:1px solid #f4ebe5;font-size:.9rem}.orders-table td::before{content:attr(data-label);display:block;margin-bottom:4px;color:#8a776c;font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase}.orders-table td:nth-child(1),.orders-table td:nth-child(3),.orders-table td:nth-child(6),.orders-table td:nth-child(9),.orders-table td:nth-child(10),.orders-table td.empty{grid-column:1/-1}.orders-table td:nth-child(9),.orders-table td:nth-child(10){border-bottom:0}.order-status-form{grid-template-columns:minmax(0,1fr) auto}.order-status-form button{padding-inline:18px}.order-actions{grid-template-columns:repeat(2,minmax(0,1fr))}.orders-panel .pagination-wrap{padding:18px 0 0}.orders-table td.empty{padding:35px 18px}}
@media(max-width:480px){.orders-heading-actions{align-items:stretch;flex-direction:column}.orders-total{justify-content:center}.orders-table tr{grid-template-columns:1fr}.orders-table td,.orders-table td:nth-child(n){grid-column:1/-1}.order-status-form{grid-template-columns:1fr}}
</style>
@endpush

@section('content')
    <div class="page-heading"><div><h1>{{ $pageTitle }}</h1><p>{{ !empty($isFakeList) ? 'Review and manage orders marked as fake.' : 'Review and manage orders.' }}</p></div><div class="orders-heading-actions"><span class="orders-total">Total <strong>{{ $orders->total() }}</strong></span><a class="create-order-button" href="{{ route('admin.orders.create', ['return_to' => !empty($isFakeList) ? 'fake_'.$filter : $filter]) }}"><i class="fa-solid fa-plus"></i> Create Order</a></div></div>
    @if(session('success'))<div class="orders-flash">{{ session('success') }}</div>@endif
    @if(!empty($isFakeList))<p>Automatic detection অথবা manual review-তে Fake হিসেবে চিহ্নিত order এখানে দেখাবে।</p>@endif
    @php
        $returnTo = !empty($isFakeList) ? 'fake_'.$filter : $filter;
    @endphp
    <section class="panel orders-panel">
        <div class="table-wrap"><table class="orders-table">
            <thead><tr><th>Order</th><th>Customer</th><th>Product</th><th>Phone</th><th>Email</th><th>Address</th><th>Quantity</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead>
            <tbody>
                @forelse($orders as $order)
                    <tr><td data-label="Order"><span class="order-number">#{{ $order->id }}</span>
                        @if($order->parent_order_id)<small class="order-note">একই ডেলিভারি: <a href="{{ route('admin.orders.edit', ['order' => $order->parent_order_id, 'return_to' => $returnTo]) }}">#{{ $order->parent_order_id }}</a><br>অতিরিক্ত ডেলিভারি চার্জ নেই</small>@endif
                        @foreach($order->deliveryAddons as $addon)<small class="order-note">সঙ্গে পাঠান: #{{ $addon->id }} — {{ $addon->burger_type }} × {{ $addon->quantity }}</small>@endforeach
                    </td><td data-label="Customer"><strong class="customer-name">{{ $order->name }}</strong></td><td data-label="Product"><span class="product-copy">{{ $order->burger_type ?: '—' }}</span></td><td data-label="Phone"><span class="order-contact">{{ $order->phone }}</span></td><td data-label="Email"><span class="order-email">{{ $order->email ?: '—' }}</span></td><td data-label="Address" title="{{ $order->address }}"><span class="order-address">{{ \Illuminate\Support\Str::limit($order->address, 55) }}</span></td><td data-label="Quantity"><span class="order-quantity">{{ $order->quantity }}</span></td><td data-label="Total"><span class="order-total">৳{{ number_format($order->total) }}</span></td><td data-label="Status"><form class="order-status-form" method="POST" action="{{ route('admin.orders.status', $order) }}">@csrf @method('PATCH')<select name="status" aria-label="Status for order #{{ $order->id }}"><option value="pending" @selected($order->status==='pending')>Pending</option><option value="shipping" @selected($order->status==='shipping')>Shipping</option><option value="delivered" @selected($order->status==='delivered')>Delivered</option><option value="cancelled" @selected($order->status==='cancelled')>Cancelled</option><option value="fake" @selected($order->status==='fake')>Fake</option></select><button type="submit"><i class="fa-solid fa-check"></i> Update</button></form></td><td data-label="Actions"><div class="order-actions"><a class="order-action order-action--edit" href="{{ route('admin.orders.edit', ['order' => $order, 'return_to' => $returnTo]) }}"><i class="fa-solid fa-pen"></i> Edit</a><form method="POST" action="{{ route('admin.orders.destroy', $order) }}" onsubmit="return confirm('Delete this order?')">@csrf @method('DELETE')<input type="hidden" name="return_to" value="{{ $returnTo }}"><button class="order-action order-action--delete" type="submit"><i class="fa-solid fa-trash"></i> Delete</button></form></div></td></tr>
                @empty
                    <tr><td colspan="10" class="empty"><i class="fa-regular fa-folder-open"></i> No orders found in this list.</td></tr>
                @endforelse
            </tbody>
        </table></div>
        <div class="pagination-wrap">{{ $orders->links() }}</div>
    </section>
@endsection
